# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven build and deploy


on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: enderstone # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        mysql database: 'api-tests'
        mysql user: 'username'
        mysql password: 'password'
    - name: configure maven
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: '[{"id": "enderstone", "username": "github-deploy", "password": "${{ secrets.DEPLOY_PASSWORD }}"}]'
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
